// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddRequestToCollection(arg1:string,arg2:models.Request):Promise<void>;

export function ClearHistory():Promise<void>;

export function CreateCollection(arg1:string):Promise<models.Collection>;

export function CreateEnvironment(arg1:string):Promise<models.Environment>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function ExecuteRequest(arg1:models.Request):Promise<models.Response>;

export function GetCollection(arg1:string):Promise<models.Collection>;

export function GetCollections():Promise<Array<models.Collection>>;

export function GetEnvironments():Promise<Array<models.Environment>>;

export function GetHistory(arg1:number,arg2:number):Promise<Array<models.HistoryEntry>>;

export function Greet(arg1:string):Promise<string>;

export function SetActiveEnvironment(arg1:string):Promise<void>;

export function UpdateCollection(arg1:models.Collection):Promise<void>;

export function UpdateEnvironment(arg1:models.Environment):Promise<void>;
